markdown        : redcarpet
redcarpet       :
 extensions     : ["tables"]
name            : Cloud Commander
title           : "Cloud Commander - хмарний файловий менеджер"
tagLine         : Хмарний файловий менеджер з консоллю та редактором
viewOn          : Подивитись на GitHub
download        : Завантажити
maintainedBy    : Проект підтримує
contact         : Зв'язатися з автором
yandex          : 5c03543d552e9150
metrika         : 24212803
ga              : UA-45093573-4
canonical       : ua.cloudcmd.io
repoName        : cloudcmd/ua/edit/gh-pages/last.md
improveText     : Виправити помилку на сайті
repoSource      : coderaiser/cloudcmd
image           : http://cloudcmd.io/img/logo/cloudcmd.png
favicon         : http://ua.cloudcmd.io/favicon.ico
